language: node_js
python: 3.7
dist: xenial
sudo: true
node_js: 10

branches:
  only:
  - master

before_install:
  - npm install -g serverless

install:
  - pip install -r requirements.txt --user
  - npm install

script: 
  - sls deploy --stage production